[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "core-proto"
version = "0.1.0"
description = "Generated Python Protobufs"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "protobuf>=4.25.0",
    "grpcio>=1.60.0",
]

[tool.setuptools.packages.find]
where = ["."]
