[package]
name = "core-proto"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.12"
tonic = "0.10"
prost-types = "0.12"
pbjson-types = "0.6"
protoc-gen-prost-serde = "0.3.1"

[lib]
path = "src/lib.rs"
