[package]
name = "core-proto"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.14.1"
tonic = {  version = "0.14.2", features = ["transport", "codegen"] }
serde = "1.0.228"

[lib]
path = "src/lib.rs"
