[package]
name = "core-proto"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.14.1"
tonic = "0.14.2"
prost-types = "0.12.6"
pbjson-types = "0.8.0"
protoc-gen-prost-serde = "0.3.1"
serde = "1.0.228"

[lib]
path = "src/lib.rs"
